Console.Clear();
Console.ForegroundColor = ConsoleColor.Cyan;
Console.WriteLine("--- Minhas Frutas Preferidas ---");
Thread.Sleep(1000);
Console.ForegroundColor = ConsoleColor.Red;
Console.WriteLine("1.Morango");
Thread.Sleep(1000);
Console.ForegroundColor = ConsoleColor.Yellow;
Console.WriteLine("2.Maracujá");
Thread.Sleep(1000);
Console.ForegroundColor = ConsoleColor.DarkMagenta;
Console.WriteLine("3.Uva");
Thread.Sleep(1000);
Console.ForegroundColor = ConsoleColor.Green;
Console.WriteLine("4.Manga");
Thread.Sleep(1000);  
Console.ForegroundColor = ConsoleColor.Yellow;
Console.WriteLine("5.Banana");
Console.ResetColor();